name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
      
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.1

      - run: go test *.go -coverprofile=coverage.out 
#      - run: go test *.go
      - run: go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.augustczar}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}        

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: augustczar/fc2.0-ci-go:latest
